### ISSUE TITLE
Esp32

### ISSUE THREAD

**Issue by donparlor** [Chill-Division/M5Stack-ESPHome#2]
Can this code be used with ESP32?

**Comment by ChillingSilence** [comment]
Yes the Atom Lite, Atom S3 and PoESP32 are all ESP32's.

The yaml only tells ESPHome how to use the sensors, so you can even use them with an ESP8266 or something like an ESP32 Development Board.

**Comment by donparlor** [comment]
Sorry for re-opening this thread, but I would like to know if while integrating MLX90640 with your ESPHome code I can expect to integrate it in Home Assistant and get a visual similar to this?
![r2hiSui](https://github.com/Chill-Division/M5Stack-ESPHome/assets/97048708/06cba0be-d809-44b5-b6f5-5572443cac54)

**Comment by ChillingSilence** [comment]
Yes

**Comment by donparlor** [comment]
Wonderful! Thank you @ChillingSilence! Your work with this code is great. I'll test it soon!

**Comment by ChillingSilence** [comment]
Glad to hear it, happy to help
